### ISSUE TITLE
ggmap don't work

### ISSUE THREAD

**Issue by anders-kolstad** [NTNU-VM/crosslists#14]

**Comment by anders-kolstad** [comment]
Seems like you now need something called an API key in order to acces them maps. Requires billing info.
https://stackoverflow.com/questions/52743142/is-something-wrong-with-the-ggmap-and-mapview-packages-in-r?noredirect=1&lq=1

**Comment by JamesDMSpeed** [comment]
Is there another away around this (a different package, using [Open street map](https://www.openstreetmap.org/#map=13/63.4059/10.3677) or similar?) I am reluctant to put the credit card on there in case they suddenly start charging for exceeding number of requests

**Comment by anders-kolstad** [comment]
Thanks for the tip. I ended up using leaflet() and open street maps. Works great. You can zoom in and out (requires java).
