### ISSUE TITLE
General mistakes

### ISSUE THREAD

**Issue by anders-kolstad** [NTNU-VM/crosslists#4]
1.	Rhinantus shold be Rhinanthus
2.	DwC returns Fragari instead of the correct Fragaria
3.	Auricomus repens should be Ranunculus repens
4.	Trientalis borealis should be Lysimachia europaea
5.	Betula pubescens torTuosa (missing the T)

**Comment by JamesDMSpeed** [comment]
These are errors in the original crosslist spreadsheet. They could be corrected either there or in the code.

**Comment by anders-kolstad** [comment]
Good.

**Comment by anders-kolstad** [comment]
Fixed. Trientalis and Auricomun fixed in the script, else fixed in excel crosslist.

**Comment by anders-kolstad** [comment]
NR3 : Auricimus is a sp under Ranunculus. Changed from capital to small a
